### ISSUE TITLE
[BUG] new JDate wrong example

### ISSUE THREAD

**Issue by marcopoloIR** [alihoseiny/ngx-persian#117]
according:
https://alihoseiny.github.io/ngx-persian/classes/JDate.html#source
line: 99
@example new JDate(1397, 12, 25)

input month must be in 1 base (not zero base), 
but this produce next GDate, 

month must be zero base: @example new JDate(1397, 12-1, 25)
in isValidJDate you mention this point (month number starting from zero),

please check and fix example, also write some Where this point.

**Comment by alihoseiny** [comment]
Thank you for reporting. Fixed.
