### ISSUE TITLE
ERROR TypeError: value.format is not a function

### ISSUE THREAD

**Issue by Aarony93** [alihoseiny/ngx-persian#141]
Error description:
Hi(salam),
I'm working with angular v8 and this error shows up when I try to use the "jdate" pipe.

My code img is here:
![code](https://user-images.githubusercontent.com/54362257/64881094-24e1c300-d66f-11e9-9291-55b5b3178b0b.png)

The console error img is here:
![err](https://user-images.githubusercontent.com/54362257/64880832-6c1b8400-d66e-11e9-9b5d-12a4e8aed3cc.png)

please fix this problem, thanks in advance.

**Comment by alihoseiny** [comment]
Thanks for your report. I will check this as soon as possible.

**Comment by alihoseiny** [comment]
Hello
This is not a problem of *ngx-persian*. You should pass an object of `JDate` type to this pipe, not a `Date` object.
Do you need the type conversion functionality in this pipe as well as formatting the date?

**Comment by Aarony93** [comment]
Can you write an example of an object of **JDate** to pass to this pipe?
And yes it would be great if this pipe could convert a javascript date to the object type you mentioned above.
Good job

**Comment by alihoseiny** [comment]
There is an example of using pipes in the [Test Application](https://github.com/alihoseiny/ngx-persian/tree/master/TestApplication/src/app/pipes-test). You can take a look at it. But you can create your `JDate` object any way you like.
If you need that feature, I will add that to the ngx-persian very soon.

**Comment by alihoseiny** [comment]
I've published a new version containing the change you wanted. Now you can use version **1.3.1** for passing `Date` objects and getting a human-readable Jalali date from it using the exact same pipe.

**Comment by Aarony93** [comment]
good job, thanks.
