### ISSUE TITLE
[Feature] support angular 9

### ISSUE THREAD

**Issue by timsar2** [alihoseiny/ngx-persian#372]
hi,
due to upgrading to angular 9, this package no more working.
ngx-persian@1.3.1 requires a peer of @angular/core@^7.2.0 but none is installed

**Comment by alihoseiny** [comment]
Hello and sorry for the late answer. I can not re-create the issue. Could you please give more information about the problem with angular 9 or above?

**Comment by alihoseiny** [comment]
Please try the latest version.
