### ISSUE TITLE
Build Failed because of this module!

### ISSUE THREAD

**Issue by alisaffari97** [alihoseiny/ngx-persian#411]
Hi, I use "ng build --prod" and it return this error:

ERROR in Type FaNumPipe in G:/AngularProjects/BProject/node_modules/ngx-persian/ngx-persian.d.ts is part of the declarations of 2 modules: AppModule in G:/AngularProjects/BProject/src/app/app.module.ts and NgxPersianModule in G:/AngularProjects/BProject/node_modules/ngx-persian/ngx-persian.d.ts! Please consider moving FaNumPipe in G:/AngularProjects/BProject/node_modules/ngx-persian/ngx-persian.d.ts to a higher module that imports AppModule in G:/AngularProjects/BProject/src/app/app.module.ts and NgxPersianModule in G:/AngularProjects/BProject/node_modules/ngx-persian/ngx-persian.d.ts. You can also create a new NgModule that exports and includes FaNumPipe in G:/AngularProjects/BProject/node_modules/ngx-persian/ngx-persian.d.ts then import that NgModule in AppModule in G:/AngularProjects/BProject/src/app/app.module.ts and NgxPersianModule in G:/AngularProjects/BProject/node_modules/ngx-persian/ngx-persian.d.ts.

How I can resolve this?!

**Comment by alihoseiny** [comment]
Hello.
Please try the latest version.
