### ISSUE TITLE
Seems that doesn't working with Angualr 11

### ISSUE THREAD

**Issue by Delpak** [alihoseiny/ngx-persian#567]
After following installation instruction, I get build error.
I just imported package and then declare 'FaNumPipe' in declaration part of NgModule.

**Comment by alihoseiny** [comment]
Could you please add any code for re-producing the problem?

**Comment by Sina7312** [comment]
Yep, It's not working for me either!

**Comment by alihoseiny** [comment]
I've created a new angular 11 application, added ngx-persian, and used the `faNum` pipe in it. There was no error.
Did you check your application with the test application in this repository?
Please add more information about your applications (installed packages, used features, etc) and the exact error message you get.

**Comment by alihoseiny** [comment]
Hello.
Please try the latest version.
