### ISSUE TITLE
error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.[BUG]

### ISSUE THREAD

**Issue by mohamad-d-zz** [alihoseiny/ngx-persian#591]
hi
thanks for this project, it is very useful.
i use command  "npm install ngx-persian --save " and after install i have this error in my project:

Failed to compile.

node_modules/ngx-persian/lib/ngx-persian.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-persian) which declares NgxPersianModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class NgxPersianModule {
                       ~~~~~~~~~~~~~~~~
tnx

**Comment by alihoseiny** [comment]
Hello.
Please try the latest version.
