### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by sinamoradi1375** [alihoseiny/ngx-persian#6]
سلام وقت بخیر
من توی داکیومنت ها گشتم و چیزی شبیه PersianDate Pipe ندیدم. 
اگر من جا انداختم راهنمایی کنین.
اگر هم چنین فیچری نیست لطفا اضافه کنین چون خیلی به درد بخوره که بشه با یه پایپ ساده، دیت تامی که از سمت سرور میاد رو به جلالی تبدیل کنه

**Comment by alihoseiny** [comment]
ممنون به خاطر پیشنهادتان. حتماً در نسخه‌ی بعدی این پایپ را هم اضافه می‌کنم.

**Comment by alihoseiny** [comment]
سلام
با دریافت نسخه‌ی جدید کتابخانه با استفاده از پایپ
jdate
می‌توانید تاریخ شمسی را هم فرمت‌دهی کنید.
